#! /bin/bash

NAME=embeddings-fastapi
DIR=/home/ubuntu/GTE_BGE_Embeddings
USER=ubuntu
GROUP=ubuntu
# WORKERS=2
WORKERS=1
WORKER_CLASS=uvicorn.workers.UvicornWorker
VENV=$DIR/venv/bin/activate
BIND=0.0.0.0:8080
LOG_LEVEL=info

cd $DIR
source $VENV

exec gunicorn app:app \
	--name $NAME \
	--workers $WORKERS \
        --worker-class $WORKER_CLASS \
	--user=$USER \
	--group=$GROUP \
	--bind=$BIND \
	--timeout 12000000 \
	--log-file=-
